name: Classic Shades
favicon: null
layout_spectrum: 0.00301
typography_spectrum: 0.06077
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a8300'
    - '#a9a9a9'
    - '#000000'
    - '#054b00'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.14593756664544344
purpose: []
